server:
    port: 8001
spring:
   application:
      name: provider-user-v1 # 应用程序的名字

##配置 erueka的信息,配置要去注册到哪个服务器上
eureka:
  client:
    service-url:
       defaultZone: http://user:123@localhost:1000/eureka